
--Execute after logging into user gambit--
CREATE TABLE SKILLTYPE(
    SKILLTYPE_ID NUMBER PRIMARY KEY,
    SKILLTYPE_NAME VARCHAR2(32 CHAR) UNIQUE NOT NULL,
    SKILLTYPE_DESC VARCHAR2(200 CHAR),
    IS_ACTIVE NUMBER NOT NULL,
    IS_CORE NUMBER NOT NULL
);

CREATE TABLE SKILL(
    SKILL_ID NUMBER PRIMARY KEY,
    SKILL_NAME VARCHAR2(32 CHAR) UNIQUE NOT NULL,
    IS_ACTIVE NUMBER NOT NULL
);

CREATE TABLE SKILLTYPE_SKILL(
    SKILLTYPE_ID NUMBER,
    SKILL_ID  NUMBER,
    PRIMARY KEY (SKILLTYPE_ID, SKILL_ID),
    CONSTRAINT FK_SKILLTYPE FOREIGN KEY (SKILLTYPE_ID) REFERENCES SKILLTYPE(SKILLTYPE_ID),
    CONSTRAINT FK_SKILL FOREIGN KEY (SKILL_ID) REFERENCES SKILL(SKILL_ID)
);

-- Does not include ST.IS_ACTIVE. I assume you will only look up skills if the skilltype were active to begin with.
CREATE OR REPLACE VIEW SKILLS_IN_SKILLTYPE AS SELECT
ST.SKILLTYPE_ID, ST.SKILLTYPE_NAME, ST.SKILLTYPE_DESC, ST.IS_CORE,
S.SKILL_ID, S.SKILL_NAME, S.IS_ACTIVE
FROM SKILLTYPE ST
LEFT JOIN SKILLTYPE_SKILL STS ON ST.SKILLTYPE_ID = STS.SKILLTYPE_ID
LEFT JOIN SKILL S ON S.SKILL_ID = STS.SKILL_ID;

CREATE SEQUENCE SKILLTYPE_ID_SEQ MINVALUE 1 INCREMENT BY 1 CACHE 10;
CREATE SEQUENCE SKILL_ID_SEQ MINVALUE 1 INCREMENT BY 1 CACHE 10;



CREATE TABLE LOG_SKILLTYPE(
    LOG_ID NUMBER PRIMARY KEY,
    SKILLTYPE_ID NUMBER NOT NULL,
    TIME_STAMP TIMESTAMP NOT NULL,
    OLD_SKILLTYPE_ID NUMBER,
    OLD_SKILLTYPE_NAME VARCHAR2(32 CHAR),
    OLD_SKILLTYPE_DESC VARCHAR2(128 CHAR),
    OLD_IS_ACTIVE NUMBER,
    OLD_IS_CORE NUMBER,
    NEW_SKILLTYPE_ID NUMBER,
    NEW_SKILLTYPE_NAME VARCHAR2(32 CHAR),
    NEW_SKILLTYPE_DESC VARCHAR2(128 CHAR),
    NEW_IS_ACTIVE NUMBER,
    NEW_IS_CORE NUMBER
);

CREATE TABLE LOG_SKILL(
    LOG_ID NUMBER PRIMARY KEY,
    SKILL_ID NUMBER NOT NULL,
    TIME_STAMP TIMESTAMP NOT NULL,
    OLD_SKILL_ID NUMBER,
    OLD_SKILL_NAME VARCHAR2(32 CHAR),
    OLD_IS_ACTIVE NUMBER,
    NEW_SKILL_ID NUMBER,
    NEW_SKILL_NAME VARCHAR2(32 CHAR),
    NEW_IS_ACTIVE NUMBER
);

CREATE SEQUENCE LOG_SKILLTYPE_ID_SEQ MINVALUE 1 INCREMENT BY 1 CACHE 10;
CREATE SEQUENCE LOG_SKILL_ID_SEQ MINVALUE 1 INCREMENT BY 1 CACHE 10;


-- Execute these after creating tables --
-- Execute these after creating tables --


-- Test Data
INSERT INTO SKILLTYPE VALUES (SKILLTYPE_ID_SEQ.NEXTVAL, 'Java/Microservices', 'Java/Microservices Description', 1, 1);
INSERT INTO SKILLTYPE VALUES (SKILLTYPE_ID_SEQ.NEXTVAL, 'JTA', 'JTA Description', 1, 1);
INSERT INTO SKILLTYPE VALUES (SKILLTYPE_ID_SEQ.NEXTVAL, 'PEGA', 'PEGA Description', 1, 1);
INSERT INTO SKILLTYPE VALUES (SKILLTYPE_ID_SEQ.NEXTVAL, '.NET', '.NET Description', 1, 1);
INSERT INTO SKILLTYPE VALUES (SKILLTYPE_ID_SEQ.NEXTVAL, 'Dynamics', 'Dynamics Description', 1, 1);
INSERT INTO SKILLTYPE VALUES (SKILLTYPE_ID_SEQ.NEXTVAL, 'Business Analyst', 'Business Analyst Description', 1, 1);
INSERT INTO SKILLTYPE VALUES (SKILLTYPE_ID_SEQ.NEXTVAL, 'JavaScript Web Developer', 'JavaScript Web Developer Description. Not active, is core', 0, 1);
INSERT INTO SKILLTYPE VALUES (SKILLTYPE_ID_SEQ.NEXTVAL, 'DBA', 'DBA Description. Is active, not core', 1, 0);
INSERT INTO SKILLTYPE VALUES (SKILLTYPE_ID_SEQ.NEXTVAL, 'Fortran', 'Fortran Description. Not active, not core', 0, 0);

INSERT INTO SKILL VALUES (SKILL_ID_SEQ.NEXTVAL, 'Visual Basic', 1);
INSERT INTO SKILL VALUES (SKILL_ID_SEQ.NEXTVAL, 'F#', 1);
INSERT INTO SKILL VALUES (SKILL_ID_SEQ.NEXTVAL, 'C++', 1);
INSERT INTO SKILL VALUES (SKILL_ID_SEQ.NEXTVAL, 'Dynamics', 1);
INSERT INTO SKILL VALUES (SKILL_ID_SEQ.NEXTVAL, 'Sales', 1);
INSERT INTO SKILL VALUES (SKILL_ID_SEQ.NEXTVAL, 'Economics', 1);
INSERT INTO SKILL VALUES (SKILL_ID_SEQ.NEXTVAL, 'Fortran', 0);
INSERT INTO SKILL VALUES (SKILL_ID_SEQ.NEXTVAL, 'Java', 1);
INSERT INTO SKILL VALUES (SKILL_ID_SEQ.NEXTVAL, 'JavaScript', 1);
INSERT INTO SKILL VALUES (SKILL_ID_SEQ.NEXTVAL, 'PL/SQL', 1);
INSERT INTO SKILL VALUES (SKILL_ID_SEQ.NEXTVAL, 'MySQL', 1);
INSERT INTO SKILL VALUES (SKILL_ID_SEQ.NEXTVAL, 'PostgreSQL', 1);
INSERT INTO SKILL VALUES (SKILL_ID_SEQ.NEXTVAL, 'NoSQL', 1);
INSERT INTO SKILL VALUES (SKILL_ID_SEQ.NEXTVAL, 'MongoDB', 1);
INSERT INTO SKILL VALUES (SKILL_ID_SEQ.NEXTVAL, 'H2', 1);
INSERT INTO SKILL VALUES (SKILL_ID_SEQ.NEXTVAL, 'HTML', 1);
INSERT INTO SKILL VALUES (SKILL_ID_SEQ.NEXTVAL, 'CSS', 1);
INSERT INTO SKILL VALUES (SKILL_ID_SEQ.NEXTVAL, 'TypeScript', 1);
INSERT INTO SKILL VALUES (SKILL_ID_SEQ.NEXTVAL, 'Angular', 1);
INSERT INTO SKILL VALUES (SKILL_ID_SEQ.NEXTVAL, 'Hibernate', 1);
INSERT INTO SKILL VALUES (SKILL_ID_SEQ.NEXTVAL, 'Servlets', 1);
INSERT INTO SKILL VALUES (SKILL_ID_SEQ.NEXTVAL, 'JSP', 1);
INSERT INTO SKILL VALUES (SKILL_ID_SEQ.NEXTVAL, 'Spring', 1);
INSERT INTO SKILL VALUES (SKILL_ID_SEQ.NEXTVAL, 'Microservices', 1);
INSERT INTO SKILL VALUES (SKILL_ID_SEQ.NEXTVAL, 'REST', 1);
INSERT INTO SKILL VALUES (SKILL_ID_SEQ.NEXTVAL, 'SOAP', 1);
INSERT INTO SKILL VALUES (SKILL_ID_SEQ.NEXTVAL, 'DevOps', 1);
INSERT INTO SKILL VALUES (SKILL_ID_SEQ.NEXTVAL, 'Git', 1);
INSERT INTO SKILL VALUES (SKILL_ID_SEQ.NEXTVAL, 'C#', 1);
INSERT INTO SKILL VALUES (SKILL_ID_SEQ.NEXTVAL, 'ASP.NET', 1);
INSERT INTO SKILL VALUES (SKILL_ID_SEQ.NEXTVAL, 'Azure', 1);
INSERT INTO SKILL VALUES (SKILL_ID_SEQ.NEXTVAL, 'AJAX', 1);
INSERT INTO SKILL VALUES (SKILL_ID_SEQ.NEXTVAL, 'JSON', 1);
INSERT INTO SKILL VALUES (SKILL_ID_SEQ.NEXTVAL, 'JUnit', 1);
INSERT INTO SKILL VALUES (SKILL_ID_SEQ.NEXTVAL, 'JDBC', 1);
INSERT INTO SKILL VALUES (SKILL_ID_SEQ.NEXTVAL, 'Selenium', 1);
INSERT INTO SKILL VALUES (SKILL_ID_SEQ.NEXTVAL, 'Cucumber', 1);
INSERT INTO SKILL VALUES (SKILL_ID_SEQ.NEXTVAL, 'Karma', 1);
INSERT INTO SKILL VALUES (SKILL_ID_SEQ.NEXTVAL, 'Agile', 1);
INSERT INTO SKILL VALUES (SKILL_ID_SEQ.NEXTVAL, 'Scrum', 1);
INSERT INTO SKILL VALUES (SKILL_ID_SEQ.NEXTVAL, 'PEGA', 1);

INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = 'Java/Microservices'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'Java'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = 'Java/Microservices'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'Spring'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = 'Java/Microservices'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'JUnit'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = 'Java/Microservices'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'Hibernate'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = 'Java/Microservices'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'HTML'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = 'Java/Microservices'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'JavaScript'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = 'Java/Microservices'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'CSS'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = 'Java/Microservices'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'Angular'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = 'Java/Microservices'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'PL/SQL'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = 'Java/Microservices'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'Microservices'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = 'Java/Microservices'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'Scrum'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = 'Java/Microservices'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'Agile'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = 'Java/Microservices'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'DevOps'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = 'Java/Microservices'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'TypeScript'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = 'Java/Microservices'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'JDBC'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = 'Java/Microservices'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'Git'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = 'Java/Microservices'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'AJAX'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = 'Java/Microservices'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'JSON'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = 'Java/Microservices'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'Servlets'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = 'Java/Microservices'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'REST'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = 'Java/Microservices'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'SOAP'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = 'JTA'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'Java'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = 'JTA'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'JUnit'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = 'JTA'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'Selenium'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = 'JTA'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'Cucumber'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = 'JTA'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'PL/SQL'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = 'JTA'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'Karma'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = 'JTA'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'Agile'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = 'JTA'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'Scrum'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = 'JTA'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'Git'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = 'PEGA'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'Java'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = 'PEGA'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'PEGA'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = 'PEGA'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'PL/SQL'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = 'PEGA'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'JavaScript'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = 'PEGA'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'HTML'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = 'PEGA'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'CSS'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = '.NET'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'C#'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = '.NET'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'F#'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = '.NET'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'Azure'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = '.NET'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'ASP.NET'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = '.NET'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'DevOps'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = '.NET'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'Agile'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = '.NET'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'Scrum'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = '.NET'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'SOAP'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = '.NET'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'REST'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = 'Dynamics'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'REST'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = 'Dynamics'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'SOAP'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = 'Dynamics'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'Azure'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = 'Dynamics'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'C#'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = 'Dynamics'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'Agile'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = 'Dynamics'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'Scrum'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = 'Dynamics'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'Sales'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = 'Business Analyst'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'Economics'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = 'Business Analyst'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'Sales'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = 'Business Analyst'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'Java'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = 'JavaScript Web Developer'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'JavaScript'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = 'JavaScript Web Developer'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'Angular'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = 'JavaScript Web Developer'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'HTML'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = 'JavaScript Web Developer'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'CSS'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = 'JavaScript Web Developer'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'AJAX'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = 'JavaScript Web Developer'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'REST'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = 'JavaScript Web Developer'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'SOAP'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = 'JavaScript Web Developer'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'MongoDB'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = 'JavaScript Web Developer'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'Karma'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = 'JavaScript Web Developer'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'Git'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = 'DBA'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'MySQL'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = 'DBA'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'PL/SQL'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = 'DBA'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'MongoDB'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = 'DBA'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'PostgreSQL'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = 'DBA'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'NoSQL'));
INSERT INTO SKILLTYPE_SKILL VALUES ((SELECT SKILLTYPE_ID FROM SKILLTYPE WHERE SKILLTYPE_NAME = 'Fortran'),
    (SELECT SKILL_ID FROM SKILL WHERE SKILL_NAME = 'Fortran'));
